import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import { cn } from "@/lib/utils";

import "./globals.css";

const poppins = Poppins({
	weight: ["400", "500", "600", "700"],
	fallback: ["sans-serif"],
	preload: true,
	display: "swap",
	subsets: ["latin"]
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({ children }: Readonly<AppLayoutProps>) {
	return (
		<html lang="en">
			<body className={cn(poppins.className, "antialiased")}>{children}</body>
		</html>
	);
}
